<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%--member_jsons.jsp(데이터 출력형식이 JSON!!) --%>
<%-- 
{
  code:'success'
  ,
  data:{
         member:[{
                  name:'나길동',
                  id:'gildong1',
                  sno:'930206-1012345'
                 },
                 {
                  name:'너길동',
                  id:'gildong2',
                  sno:'940206-1012345'
                 },
                 {
                  name:'우리길동',
                  id:'gildong3',
                  sno:'950206-1012345'
                 },
                ]
       }
}
--%>
<%--member_jsons.jsp(데이터 출력형식이 JSON!!) --%>
[
  {
    name:'나길동',
    id:'gildong1',
    sno:'930206-1012345'
   },
  {
    name:'너길동',
    id:'gildong2',
    sno:'940206-1012345'
   },
  {
    name:'우리길동',
    id:'gildong3',
    sno:'950206-1012345'
   }
]